[project]
name = "flux-triton"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "diffusers>=0.35.1",
    "pillow>=11.3.0",
    "sentencepiece>=0.2.1",
    "torch>=2.8.0",
    "transformers>=4.56.2",
    "tritonclient[all]>=2.60.0",
]
